### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by RizRiyz** [valutac/gitnore#1]
I think we also need multiple language support

`$ gitnore -i python,java,c`

**Comment by ngurajeka** [comment]
Of course, we can try to concat the `[]byte` of the gitignore files.

**Comment by EnKrypt** [comment]
Submitted a pull request that fixes this. Do review in your spare time.

**Comment by RizRiyz** [comment]
@EnKrypt that's awesome! let us check it first
